---
name: Sonarqube
on:
  push:
    branches:
      - "*"
jobs:
  build:
    env:
      PROJ_SONAR_TOKEN: '7a49bd0dbb8959e270f0b64da91898b61a34ffe7'
      SONARQUBE_SERVER_URL: 'http://a417c2f372c6b457788f0a244010ecca-264646901.ap-southeast-1.elb.amazonaws.com:9000'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          DISTRIBUTION: 'adopt'
          java-version: "11"
      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
             -Dsonar.host.url=$SONARQUBE_SERVER_URL \
             -Dsonar.login=$PROJ_SONAR_TOKEN
