---
name: Sonarqube
on:
  push:
    branches:
      - "*"
jobs:
  build:
    env:
      PROJ_SONAR_TOKEN: fsdgsdgddf4444
      SONARQUBE_SERVER_URL: http://cccccuyfgggggggggg:4849
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: adopt
          java-version: "11"
      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
             -Dsonar.host.url=${{SONARQUBE_SERVER_URL}} \
             -Dsonar.login=${{PROJ_SONAR_TOKEN}}
